app:
  version: "0.1-dev"
  debug: true
  env: "dev"
grpc:
  host: "localhost"
  port: 55283
secrets:
  redis:
    replicaset: true
    masterName: mymaster
    sentinels:
      - "sentinel-0:5000"
      - "sentinel-1:5000"
    pass: a-very-complex-password-here
    sentinel_pass: a-very-complex-password-here
  sentry_dsn: ""
storage_path: "/.volumes/casty_storage"
