app:
  version: "0.1-dev"
  debug: true
  env: "dev"
grpc:
  host: "localhost"
  port: 55283
secrets:
  redis:
    masterName: mymaster
    sentinels:
      - "sentinel-0:5000"
      - "sentinel-1:5000"
    pass: "super-secure-password"
  sentry_dsn: ""
storage_path: "/Users/josh/.volumes/casty_storage"